from django.urls import path
from homework import views

urlpatterns = [
    path("", views.HomeworkClassListView.as_view(), name="homework_class_list"),
    path(
        "create/", views.HomeworkClassCreateView.as_view(), name="homework_class_create"
    ),
    path(
        "<slug:slug>/",
        views.HomeworkClassDetailView.as_view(),
        name="homework_class_detail",
    ),
    path(
        "<slug:slug>/edit/",
        views.HomeworkClassEditView.as_view(),
        name="homework_class_edit",
    ),
    path(
        "<slug:slug>/delete/",
        views.HomeworkClassDeleteView.as_view(),
        name="homework_class_delete",
    ),
    path(
        "<slug:slug>/students/",
        views.HomeworkClassStudentsView.as_view(),
        name="homework_class_students",
    ),
    path(
        "<slug:slug>/students/<int:student_id>/",
        views.HomeworkStudentDetailView.as_view(),
        name="homework_student_detail",
    ),
    path(
        "<slug:slug>/students/<int:student_id>/remove/",
        views.HomeworkRemoveStudentView.as_view(),
        name="homework_remove_student",
    ),
    path(
        "<slug:slug>/my-submissions/",
        views.HomeworkMySubmissionsView.as_view(),
        name="homework_my_submissions",
    ),
    path(
        "<slug:slug>/join/",
        views.HomeworkJoinRequestView.as_view(),
        name="homework_join_request",
    ),
    path(
        "<slug:slug>/join-requests/",
        views.HomeworkJoinRequestsListView.as_view(),
        name="homework_join_requests",
    ),
    path(
        "<slug:slug>/join-requests/<int:request_id>/approve/",
        views.HomeworkApproveJoinView.as_view(),
        name="homework_approve_join",
    ),
    path(
        "<slug:slug>/join-requests/<int:request_id>/reject/",
        views.HomeworkRejectJoinView.as_view(),
        name="homework_reject_join",
    ),
    path(
        "<slug:class_slug>/assignments/create/",
        views.HomeworkAssignmentCreateView.as_view(),
        name="homework_assignment_create",
    ),
    path(
        "<slug:class_slug>/assignments/<int:pk>/",
        views.HomeworkAssignmentDetailView.as_view(),
        name="homework_assignment_detail",
    ),
    path(
        "<slug:class_slug>/assignments/<int:pk>/edit/",
        views.HomeworkAssignmentEditView.as_view(),
        name="homework_assignment_edit",
    ),
    path(
        "<slug:class_slug>/assignments/<int:pk>/images/<int:image_id>/delete/",
        views.HomeworkAssignmentImageDeleteView.as_view(),
        name="homework_assignment_image_delete",
    ),
    path(
        "<slug:class_slug>/assignments/<int:pk>/submit/",
        views.HomeworkSubmitView.as_view(),
        name="homework_submit",
    ),
    path(
        "<slug:class_slug>/assignments/<int:pk>/submissions/",
        views.HomeworkAllSubmissionsView.as_view(),
        name="homework_all_submissions",
    ),
    path(
        "<slug:class_slug>/assignments/<int:pk>/submissions/<int:submission_pk>/",
        views.HomeworkSubmissionDetailView.as_view(),
        name="homework_submission_detail",
    ),
    path(
        "<slug:class_slug>/assignments/<int:pk>/submissions/<int:submission_pk>/grade/",
        views.HomeworkGradeView.as_view(),
        name="homework_grade",
    ),
]
