# Generated by Django 3.2.25 on 2025-12-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0189_add_problem_show_testcases"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hide the leaderboard from public view",
                        verbose_name="Hide leaderboard",
                    ),
                ),
                (
                    "hidden_message",
                    models.TextField(
                        blank=True,
                        default="Bảng xếp hạng đang được ẩn, vui lòng quay lại sau",
                        verbose_name="Hidden message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leaderboard Configuration",
                "verbose_name_plural": "Leaderboard Configuration",
            },
        ),
    ]
