# Generated by Django 3.2.25 on 2025-12-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0190_leaderboard_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboardconfig",
            options={
                "verbose_name": "leaderboard configuration",
                "verbose_name_plural": "leaderboard configuration",
            },
        ),
    ]
