# Generated by Django 3.2.25 on 2025-12-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0191_alter_leaderboardconfig_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardconfig",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can view the leaderboard even when it's hidden",
                related_name="can_view_hidden_leaderboard",
                to="judge.Profile",
                verbose_name="Allowed users",
            ),
        ),
    ]
