# Generated by Django 3.2.25 on 2026-01-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("judge", "0192_leaderboardconfig_allowed_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMaintenance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Khi bật, website sẽ hiển thị trang đóng cửa cho người dùng không được phép",
                        verbose_name="Đóng website",
                    ),
                ),
                (
                    "closure_message",
                    models.TextField(
                        blank=True,
                        default="Website đang được bảo trì. Vui lòng quay lại sau.",
                        help_text="Thông báo hiển thị khi website đóng cửa",
                        verbose_name="Thông báo đóng cửa",
                    ),
                ),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Các nhóm (roles) có thể truy cập website khi đóng cửa",
                        related_name="can_access_closed_site",
                        to="auth.Group",
                        verbose_name="Nhóm được phép",
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Những người dùng có thể truy cập website khi đóng cửa (ngoài superuser)",
                        related_name="can_access_closed_site",
                        to="judge.Profile",
                        verbose_name="Người dùng được phép",
                    ),
                ),
            ],
            options={
                "verbose_name": "cấu hình bảo trì website",
                "verbose_name_plural": "cấu hình bảo trì website",
            },
        ),
    ]
