# Generated by Django 3.2.25 on 2026-02-03 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judge", "0193_add_site_maintenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TetWish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=500, verbose_name="Lời chúc")),
                (
                    "is_from_superadmin",
                    models.BooleanField(default=False, verbose_name="Từ Superadmin"),
                ),
                (
                    "is_broadcast",
                    models.BooleanField(default=False, verbose_name="Gửi cho tất cả"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Thời gian gửi"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_wishes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhận",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_wishes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lời chúc Tết",
                "verbose_name_plural": "Lời chúc Tết",
                "ordering": ["-created_at"],
                "unique_together": {("sender", "receiver")},
            },
        ),
    ]
