# Generated by Django 3.2.25 on 2026-02-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0194_tetwish"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tetwish",
            unique_together=set(),
        ),
    ]
