# Generated by Django 3.2.25 on 2026-02-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judge", "0195_alter_tetwish_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TetWishLimit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_wishes",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Số lời chúc tối đa"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_wish_limits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tet_wish_limit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giới hạn lời chúc",
                "verbose_name_plural": "Giới hạn lời chúc",
            },
        ),
    ]
