# Generated by Django 3.2.25 on 2026-02-03 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judge", "0196_tetwishlimit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tetwishlimit",
            options={
                "verbose_name": "Giới hạn gửi lời chúc",
                "verbose_name_plural": "Giới hạn gửi lời chúc",
            },
        ),
        migrations.RemoveField(
            model_name="tetwishlimit",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="tetwishlimit",
            name="set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="set_limits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người đặt giới hạn",
            ),
        ),
        migrations.AlterField(
            model_name="tetwishlimit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc"),
        ),
    ]
