# Generated by Django 3.2.25 on 2026-02-03 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judge", "0197_auto_20260203_2304"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewYearGreeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "greeting_type",
                    models.CharField(
                        choices=[
                            ("clb_intro", "Lời giới thiệu CLB"),
                            ("clb_wish", "Lời chúc của CLB"),
                            ("superadmin", "Lời chúc Superadmin"),
                            ("supporter", "Lời chúc Hỗ trợ"),
                            ("clb_ending", "Lời kết thúc CLB"),
                        ],
                        max_length=20,
                        verbose_name="Loại lời chúc",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tiêu đề"
                    ),
                ),
                ("message", models.TextField(verbose_name="Nội dung lời chúc")),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Tên hiển thị (nếu khác username)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thứ tự hiển thị"
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2026, verbose_name="Năm")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_year_greetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người viết",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lời chúc năm mới",
                "verbose_name_plural": "Lời chúc năm mới",
                "ordering": ["greeting_type", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewYearGreetingSeen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2026, verbose_name="Năm")),
                (
                    "seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Xem lúc"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_year_greetings_seen",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đã xem lời chúc năm mới",
                "verbose_name_plural": "Đã xem lời chúc năm mới",
                "unique_together": {("user", "year")},
            },
        ),
        migrations.CreateModel(
            name="NewYearGreetingPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_send_greeting",
                    models.BooleanField(
                        default=False, verbose_name="Được phép gửi lời chúc"
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2026, verbose_name="Năm")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cấp bởi",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_year_greeting_permission",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quyền gửi lời chúc năm mới",
                "verbose_name_plural": "Quyền gửi lời chúc năm mới",
                "unique_together": {("user", "year")},
            },
        ),
    ]
