# Generated by Django 3.2.25 on 2026-01-26 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("judge", "0193_add_site_maintenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=256, verbose_name="assignment title"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed assignment description/problem statement",
                        verbose_name="assignment description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("CODE", "Code"), ("IMAGE", "Image/File")],
                        default="CODE",
                        max_length=10,
                        verbose_name="submission type",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="deadline")),
                (
                    "allow_late_submission",
                    models.BooleanField(
                        default=False, verbose_name="allow late submission"
                    ),
                ),
                (
                    "allow_multiple_graders",
                    models.BooleanField(
                        default=False,
                        help_text="Allow multiple managers to grade the same submission",
                        verbose_name="allow multiple graders",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=10, verbose_name="max file size (MB)"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.CharField(
                        default="py,cpp,c,java,txt,zip,rar,png,jpg,jpeg,pdf",
                        help_text="Comma-separated list of allowed file extensions",
                        max_length=256,
                        verbose_name="allowed file extensions",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=1,
                        default=10.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="maximum points",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="is published"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "homework assignment",
                "verbose_name_plural": "homework assignments",
                "ordering": ["order", "-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submission date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "code_content",
                    models.TextField(blank=True, verbose_name="code content"),
                ),
                (
                    "code_language",
                    models.CharField(
                        blank=True,
                        default="python",
                        max_length=50,
                        verbose_name="programming language",
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homework_submissions/",
                        verbose_name="submission file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="original filename"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("GR", "Graded"),
                            ("RE", "Returned for revision"),
                        ],
                        default="PE",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(default=False, verbose_name="submitted late"),
                ),
                (
                    "submission_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes from the student",
                        verbose_name="student notes",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="homework.homeworkassignment",
                        verbose_name="assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_submissions",
                        to="judge.profile",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "homework submission",
                "verbose_name_plural": "homework submissions",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="class name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Class name shown in URL",
                        max_length=128,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[-a-zA-Z0-9]+$", "Only alphanumeric and hyphens"
                            )
                        ],
                        verbose_name="class slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="class description"),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="class image URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "co_managers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can manage this class",
                        related_name="co_managed_homework_classes",
                        to="judge.Profile",
                        verbose_name="co-managers",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_homework_classes",
                        to="judge.profile",
                        verbose_name="creator",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_homework_classes",
                        to="judge.Profile",
                        verbose_name="students",
                    ),
                ),
            ],
            options={
                "verbose_name": "homework class",
                "verbose_name_plural": "homework classes",
                "ordering": ["-creation_date"],
            },
        ),
        migrations.AddField(
            model_name="homeworkassignment",
            name="homework_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="homework.homeworkclass",
                verbose_name="class",
            ),
        ),
        migrations.CreateModel(
            name="HomeworkGrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="score",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="feedback")),
                (
                    "graded_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="graded date"),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graded_homeworks",
                        to="judge.profile",
                        verbose_name="grader",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="homework.homeworksubmission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "homework grade",
                "verbose_name_plural": "homework grades",
                "ordering": ["-graded_date"],
                "unique_together": {("submission", "grader")},
            },
        ),
    ]
