# Generated by Django 3.2.25 on 2026-01-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0193_add_site_maintenance"),
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkJoinRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("AP", "Approved"),
                            ("RE", "Rejected"),
                        ],
                        default="PE",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="request date"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed date"
                    ),
                ),
                (
                    "homework_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="homework.homeworkclass",
                        verbose_name="class",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_join_requests",
                        to="judge.profile",
                        verbose_name="requester",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_join_requests",
                        to="judge.profile",
                        verbose_name="reviewed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "join request",
                "verbose_name_plural": "join requests",
                "ordering": ["-request_date"],
                "unique_together": {("homework_class", "requester")},
            },
        ),
    ]
