# Generated by Django 3.2.25 on 2026-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0002_homeworkjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="is_graded",
            field=models.BooleanField(
                default=True,
                help_text="Whether this assignment will be graded",
                verbose_name="is graded",
            ),
        ),
    ]
