# Generated by Django 3.2.25 on 2026-01-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0003_homeworkassignment_is_graded"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkSubmissionFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="homework_submissions/", verbose_name="file"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=256, verbose_name="original filename"),
                ),
                (
                    "uploaded_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="uploaded date"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="homework.homeworksubmission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission file",
                "verbose_name_plural": "submission files",
                "ordering": ["uploaded_date"],
            },
        ),
    ]
