# Generated by Django 3.2.25 on 2026-01-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0004_homeworksubmissionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworksubmission",
            name="edit_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this submission has been edited",
                verbose_name="edit count",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmissionfile",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deleted date"
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmissionfile",
            name="edit_version",
            field=models.PositiveIntegerField(default=1, verbose_name="edit version"),
        ),
        migrations.AddField(
            model_name="homeworksubmissionfile",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="File has been automatically deleted after retention period",
                verbose_name="file deleted",
            ),
        ),
        migrations.AlterField(
            model_name="homeworksubmissionfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="homework_submissions/",
                verbose_name="file",
            ),
        ),
        migrations.CreateModel(
            name="HomeworkSubmissionHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edit_version",
                    models.PositiveIntegerField(verbose_name="edit version"),
                ),
                (
                    "edited_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="edited date"),
                ),
                (
                    "code_content",
                    models.TextField(blank=True, verbose_name="code content"),
                ),
                (
                    "code_language",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="programming language"
                    ),
                ),
                (
                    "submission_notes",
                    models.TextField(blank=True, verbose_name="notes"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="homework.homeworksubmission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission history",
                "verbose_name_plural": "submission histories",
                "ordering": ["-edit_version"],
                "unique_together": {("submission", "edit_version")},
            },
        ),
    ]
