# Generated by Django 3.2.25 on 2026-01-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0005_add_submission_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkclass",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PU", "Public"),
                    ("RQ", "Request to join"),
                    ("PR", "Private"),
                ],
                default="RQ",
                help_text="Public: anyone can join. Request: need approval. Private: invite only.",
                max_length=2,
                verbose_name="visibility",
            ),
        ),
    ]
