# Generated by Django 3.2.25 on 2026-01-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0006_add_class_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkAssignmentImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="assignment_images/", verbose_name="image"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=256, verbose_name="original filename"),
                ),
                (
                    "uploaded_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="uploaded date"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="homework.homeworkassignment",
                        verbose_name="assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "assignment image",
                "verbose_name_plural": "assignment images",
                "ordering": ["order", "uploaded_date"],
            },
        ),
    ]
