# Generated by Django 3.2.25 on 2026-01-27 16:13

from django.db import migrations, models
import django.db.models.deletion
import homework.models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0007_add_assignment_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkassignmentimage",
            name="image",
            field=models.ImageField(
                upload_to=homework.models.assignment_image_upload_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="homeworksubmissionfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=homework.models.submission_file_upload_path,
                verbose_name="file",
            ),
        ),
        migrations.CreateModel(
            name="HomeworkCodeFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        default="main.py", max_length=256, verbose_name="filename"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="code content")),
                (
                    "language",
                    models.CharField(
                        default="python",
                        max_length=50,
                        verbose_name="programming language",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="updated date"),
                ),
                (
                    "edit_version",
                    models.PositiveIntegerField(default=1, verbose_name="edit version"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_files",
                        to="homework.homeworksubmission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "code file",
                "verbose_name_plural": "code files",
                "ordering": ["order", "created_date"],
            },
        ),
    ]
