# Generated by Django 3.2.25 on 2026-01-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0193_add_site_maintenance"),
        ("homework", "0008_add_code_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkclass",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_homework_classes",
                to="judge.profile",
                verbose_name="assistant manager",
            ),
        ),
    ]
